data:
  train_files: OpenLeecher/prompt_dataset@train
  val_files: OpenLeecher/prompt_dataset@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 750
  max_response_length: 2050
  rollout_batch_size: 24
  val_batch_size: 1024
  format_prompt: ./examples/format_prompt/basic_format.jinja
  shuffle: false
  seed: 1
  max_pixels: 4194304
  min_pixels: 262144
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 0.002

worker:
  actor:
    global_batch_size: 24
    micro_batch_size_per_device_for_update: 4
    micro_batch_size_per_device_for_experience: 16
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: OpenLeecher/story_gen_grpo
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1e-6
      weight_decay: 0.05
      strategy: adamw_bf16  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.05
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
      torch_dtype: bf16
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 8
    temperature: 1.0
    top_p: 0.99
    gpu_memory_utilization: 0.5
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    limit_images: 0
    val_override_config:
      temperature: 0.7
      top_p: 0.9
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: function
    reward_function: ./examples/reward_function/story.py:compute_score

trainer:
  total_episodes: 1
  logger: ["console", "wandb"]
  project_name: easy_r1
  experiment_name: story_gen
  n_gpus_per_node: 1
  nnodes: 1
  val_freq: 5  # -1 to disable
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 5  # -1 to disable
  save_limit: 3  # -1 to disable
  save_checkpoint_path: null
  load_checkpoint_path: null
